theme: jekyll-theme-architect

<!DOCTYPE html>
<html>
	<head>
		<title> Wanrong Chen</title>
		<!-- link to main stylesheet -->
		<link rel="stylesheet" type="text/css" href="/css/main.css"
>
	</head>
	<body>
		<nav>
    		<ul>
        		<li><a href="/">Home</a></li>
	        	<li><a href="/about">About</a></li>
        		<li><a href="/cv">CV</a></li>
        		<li><a href="/blog">Blog</a></li>
    		</ul>
		</nav>
		<div class="container">
    		<div class="blurb">
        		<h1>Hi there, I'm Wanrong!</h1>
				<p>I'm best known as the horrible cop from <em>A Touch of Evil</em> Don't trust me. <a href="/about">Read more about my life...</a></p>
    		</div><!-- /.blurb -->
		</div><!-- /.container -->
		<footer>
    		<li><a href="mailto:beverly525.chen@outlook.com">email</a></li>
        		<li><a href="https://github.com/wanrong1890chen">github.com/wanrong1890chen</a></li>
			</ul>
		</footer>
	</body>
</html>
